import React from 'react';

const QuotationsAddLayoutPage = () => {
  return (
    <div style={containerStyle}>
      <div style={headerStyle}>
        <h1 style={titleStyle}>Create a new Quotation</h1>
        <p style={subtitleStyle}>Fill in the details below to create a new quotation</p>
      </div>

      <div style={formContainerStyle}>
        {/* Quotation Information Section */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>📋</div>
            <h3 style={cardHeaderStyle}>Quotation Information</h3>
          </div>
          <div style={fieldsGridStyle}>
            <Field 
              label="Quotation ID" 
              placeholder="Enter Quotation ID" 
            />
            <Field 
              label="Quotation Title" 
              placeholder="Enter Quotation Title" 
            />
            <Field 
              label="Lead Details" 
              type="select" 
              placeholder="Select Lead" 
              options={['Lead 1', 'Lead 2']}
            />
            <Field 
              label="Lead ID" 
              placeholder="Enter Lead ID" 
            />
            <Field 
              label="Transaction Type" 
              type="select" 
              placeholder="Select Type" 
              options={['Rent', 'Buy']}
            />
            <Field 
              label="Quotation Status" 
              type="select" 
              placeholder="Select Status" 
              options={['New', 'Sent', 'Accepted']}
            />
            <Field 
              label="Source of Enquiry" 
              type="select" 
              placeholder="Select Source" 
              options={['Search Engine', 'Referral', 'Advertisement']}
            />
            <Field 
              label="Owner" 
              placeholder="Enter Owner Name" 
            />
            <Field 
              label="Remarks" 
              placeholder="Enter Remarks" 
              type="textarea"
            />
            <Field 
              label="Quotation Generated By" 
              placeholder="Enter Name" 
            />
            <div style={{ gridColumn: '1 / -1' }}>
              <Checkbox 
                label="Active Status" 
                description="Enable this quotation in the system"
              />
            </div>
          </div>
        </div>

        {/* Personal Details Section */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>👤</div>
            <h3 style={cardHeaderStyle}>Personal Details</h3>
          </div>
          <div style={fieldsGridStyle}>
            <Field 
              label="First Name" 
              placeholder="Enter First Name" 
            />
            <Field 
              label="Last Name" 
              placeholder="Enter Last Name" 
            />
            <Field 
              label="Email ID" 
              placeholder="Enter Email" 
              type="email"
            />
            <Field 
              label="Phone Number" 
              placeholder="Enter Phone Number" 
              type="tel"
            />
            <Field 
              label="Rental Duration (Months)" 
              placeholder="Enter Duration" 
              type="number"
            />
            <Field 
              label="Rental Start Date" 
              type="date" 
              placeholder="Select Date" 
            />
            <Field 
              label="Rental End Date" 
              type="date" 
              placeholder="Select Date" 
            />
            <Field 
              label="Quotation Date" 
              type="date" 
              placeholder="Select Date" 
            />
            <Field 
              label="Industry" 
              placeholder="Enter Industry" 
            />
          </div>
        </div>

        {/* Address Section */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>🏠</div>
            <h3 style={cardHeaderStyle}>Address</h3>
          </div>
          <div style={fieldsGridStyle}>
            <Field 
              label="Street" 
              placeholder="Enter Street" 
            />
            <Field 
              label="Landmark" 
              placeholder="Enter Landmark" 
            />
            <Field 
              label="Pincode" 
              placeholder="Enter Pincode" 
              type="number"
            />
            <Field 
              label="City" 
              placeholder="Enter City" 
              value="Bangalore"
            />
            <Field 
              label="State" 
              placeholder="Enter State" 
              value="Karnataka"
            />
            <Field 
              label="Country" 
              placeholder="Enter Country" 
              value="India"
            />
          </div>
        </div>
      </div>

      {/* Selected Products Section */}
      <div style={productsSectionStyle}>
        <h3 style={sectionTitleStyle}>Selected Products</h3>
        <button style={selectProductBtnStyle}>
          Select Product
        </button>
      </div>

      {/* Action Buttons */}
      <div style={buttonContainerStyle}>
        <button style={cancelBtnStyle} onMouseEnter={(e) => e.target.style.backgroundColor = '#e5e7eb'} onMouseLeave={(e) => e.target.style.backgroundColor = '#f3f4f6'}>
          Cancel
        </button>
        <button style={createBtnStyle} onMouseEnter={(e) => e.target.style.backgroundColor = '#1d4ed8'} onMouseLeave={(e) => e.target.style.backgroundColor = '#2563eb'}>
          Create Quotation
        </button>
      </div>
    </div>
  );
};

const Field = ({ label, placeholder, type = 'text', options = [], value }) => (
  <div style={fieldContainerStyle}>
    <label style={labelStyle}>
      {label}
    </label>
    {type === 'select' ? (
      <div style={selectWrapperStyle}>
        <select 
          style={selectStyle} 
          defaultValue=""
        >
          <option value="" disabled>{placeholder}</option>
          {options.map((option, idx) => (
            <option key={idx} value={option}>{option}</option>
          ))}
        </select>
        <div style={selectArrowStyle}>▼</div>
      </div>
    ) : type === 'textarea' ? (
      <textarea
        placeholder={placeholder}
        style={textareaStyle}
        rows={3}
      />
    ) : type === 'date' ? (
      <input
        type="date"
        placeholder={placeholder}
        style={inputStyle}
      />
    ) : (
      <input
        type={type}
        placeholder={placeholder}
        style={inputStyle}
        value={value}
        readOnly={!!value}
      />
    )}
  </div>
);

const Checkbox = ({ label, description }) => (
  <div style={checkboxContainerStyle}>
    <label style={checkboxLabelStyle}>
      <input 
        type="checkbox" 
        style={checkboxStyle}
        defaultChecked
      />
      <div style={checkboxCustomStyle}>
        <span style={checkmarkStyle}>✓</span>
      </div>
      <div>
        <span style={checkboxTextStyle}>{label}</span>
        <span style={checkboxDescStyle}>{description}</span>
      </div>
    </label>
  </div>
);

// Styles (consistent with the previous examples)
const containerStyle = {
  padding: '2rem',
  fontFamily: '"Inter", "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif',
  minHeight: '100vh',
  lineHeight: 1.6,
};

const headerStyle = {
  marginBottom: '2rem',
  maxWidth: '1400px',
};

const titleStyle = {
  fontSize: '2rem',
  fontWeight: '700',
  color: '#1e293b',
  margin: '0 0 0.5rem 0',
  letterSpacing: '-0.025em',
};

const subtitleStyle = {
  fontSize: '1rem',
  color: '#64748b',
  margin: 0,
};

const formContainerStyle = {
  display: 'grid',
  gap: '1.5rem',
  maxWidth: '1400px',
  gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
};

const cardStyle = {
  backgroundColor: '#ffffff',
  padding: '1.5rem',
  borderRadius: '12px',
  boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
  border: '1px solid #e2e8f0',
  transition: 'box-shadow 0.2s ease',
};

const cardHeaderContainerStyle = {
  display: 'flex',
  alignItems: 'center',
  marginBottom: '1.5rem',
  paddingBottom: '1rem',
  borderBottom: '1px solid #e2e8f0',
};

const iconStyle = {
  fontSize: '1.25rem',
  marginRight: '0.75rem',
  backgroundColor: '#f1f5f9',
  padding: '0.5rem',
  borderRadius: '8px',
};

const cardHeaderStyle = {
  fontSize: '1.125rem',
  fontWeight: '600',
  color: '#1e293b',
  margin: 0,
};

const fieldsGridStyle = {
  display: 'grid',
  gap: '1rem',
  gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
};

const fieldContainerStyle = {
  display: 'flex',
  flexDirection: 'column',
};

const labelStyle = {
  display: 'block',
  marginBottom: '0.5rem',
  fontWeight: '500',
  fontSize: '0.875rem',
  color: '#374151',
  letterSpacing: '0.025em',
};

const inputStyle = {
  width: '100%',
  padding: '0.75rem',
  borderRadius: '8px',
  border: '1px solid #d1d5db',
  fontSize: '0.875rem',
  backgroundColor: '#ffffff',
  transition: 'all 0.2s ease',
  outline: 'none',
  boxSizing: 'border-box',
};

const selectWrapperStyle = {
  position: 'relative',
  width: '100%',
};

const selectStyle = {
  width: '100%',
  padding: '0.75rem',
  paddingRight: '2.5rem',
  borderRadius: '8px',
  border: '1px solid #d1d5db',
  fontSize: '0.875rem',
  backgroundColor: '#ffffff',
  appearance: 'none',
  transition: 'all 0.2s ease',
  outline: 'none',
  boxSizing: 'border-box',
  cursor: 'pointer',
};

const selectArrowStyle = {
  position: 'absolute',
  right: '0.75rem',
  top: '50%',
  transform: 'translateY(-50%)',
  pointerEvents: 'none',
  fontSize: '0.75rem',
  color: '#6b7280',
};

const textareaStyle = {
  width: '100%',
  padding: '0.75rem',
  borderRadius: '8px',
  border: '1px solid #d1d5db',
  fontSize: '0.875rem',
  backgroundColor: '#ffffff',
  transition: 'all 0.2s ease',
  outline: 'none',
  resize: 'vertical',
  fontFamily: 'inherit',
  boxSizing: 'border-box',
};

const checkboxContainerStyle = {
  marginTop: '0.5rem',
};

const checkboxLabelStyle = {
  display: 'flex',
  alignItems: 'flex-start',
  cursor: 'pointer',
  gap: '0.75rem',
};

const checkboxStyle = {
  display: 'none',
};

const checkboxCustomStyle = {
  width: '20px',
  height: '20px',
  borderRadius: '4px',
  border: '2px solid #d1d5db',
  backgroundColor: '#2563eb',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'all 0.2s ease',
  flexShrink: 0,
  marginTop: '2px',
};

const checkmarkStyle = {
  color: '#ffffff',
  fontSize: '12px',
  fontWeight: 'bold',
};

const checkboxTextStyle = {
  fontSize: '0.875rem',
  fontWeight: '500',
  color: '#374151',
  display: 'block',
};

const checkboxDescStyle = {
  fontSize: '0.75rem',
  color: '#6b7280',
  display: 'block',
  marginTop: '0.25rem',
};

const buttonContainerStyle = {
  display: 'flex',
  justifyContent: 'flex-end',
  gap: '0.75rem',
  marginTop: '2rem',
  maxWidth: '1200px',
  margin: '2rem auto 0',
  padding: '0 1.5rem',
};

const cancelBtnStyle = {
  padding: '0.75rem 1.5rem',
  backgroundColor: '#f3f4f6',
  color: '#374151',
  border: '1px solid #d1d5db',
  borderRadius: '8px',
  cursor: 'pointer',
  fontSize: '0.875rem',
  fontWeight: '500',
  transition: 'all 0.2s ease',
  outline: 'none',
};

const createBtnStyle = {
  padding: '0.75rem 1.5rem',
  backgroundColor: '#2563eb',
  color: 'white',
  border: 'none',
  borderRadius: '8px',
  cursor: 'pointer',
  fontSize: '0.875rem',
  fontWeight: '500',
  transition: 'all 0.2s ease',
  outline: 'none',
};

const productsSectionStyle = {
  maxWidth: '1200px',
  margin: '0 auto',
  padding: '0 1.5rem',
};

const sectionTitleStyle = {
  fontSize: '1rem',
  fontWeight: '600',
  color: '#374151',
  marginBottom: '1rem',
};

const selectProductBtnStyle = {
  padding: '0.75rem 1.5rem',
  backgroundColor: '#ffffff',
  color: '#2563eb',
  border: '1px solid #2563eb',
  borderRadius: '8px',
  cursor: 'pointer',
  fontSize: '0.875rem',
  fontWeight: '500',
  transition: 'all 0.2s ease',
  outline: 'none',
};

export default QuotationsAddLayoutPage;