import React from 'react';
import {
  TextField,
  MenuItem,
  FormControlLabel,
  Checkbox,
  Typography,
  Button,
} from '@mui/material';

const SalesOrdersEditLayoutPage = () => {
  return (
    <div style={containerStyle}>
      <h2 style={headingStyle}>Edit Order</h2>

      <div style={formSectionStyle}>
        {/* Column 1: Order Information */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>🧾</div>
            <h3 style={cardHeaderStyle}>Order Information</h3>
          </div>
          <div style={fieldsGridStyle}>
            <StyledTextField label="Order ID" value="ORD123456" />
            <StyledTextField label="Order Title" value="Corporate Laptop Rental" />
            <StyledSelectField label="Quotation Details" options={["Select Quotation", "Quotation A"]} value="Quotation A" />
            <StyledTextField label="Quotation ID" value="QT56789" />
            <StyledSelectField label="Transaction Type" options={["Rent", "Sale"]} value="Rent" />
            <StyledSelectField label="Payment Type" options={["Prepaid", "Postpaid"]} value="Prepaid" />
            <StyledSelectField label="Order Status" options={["Pending", "Confirmed", "Cancelled"]} value="Confirmed" />
            <StyledSelectField label="Source of Enquiry" options={["Search Engine", "Referral", "Walk-in"]} value="Referral" />
            <StyledTextField label="Owner" value="John Doe" />
            <StyledTextField label="Remarks" multiline rows={2} value="Urgent delivery required." />
            <StyledTextField label="Order Generated By" value="rounder" disabled />
            <div style={{ gridColumn: '1 / -1', marginTop: '0.5rem' }}>
              <Typography variant="body1" style={{ fontWeight: 500 }}>Control:</Typography>
              <FormControlLabel
                control={<Checkbox defaultChecked />}
                label="Active Status"
              />
            </div>
          </div>
        </div>

        {/* Column 2: Personal Details */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>👤</div>
            <h3 style={cardHeaderStyle}>Personal Details</h3>
          </div>
          <div style={fieldsGridStyle}>
            <StyledTextField label="First Name" value="Jane" />
            <StyledTextField label="Last Name" value="Smith" />
            <StyledTextField label="Email ID" value="jane.smith@example.com" />
            <StyledTextField label="Phone Number" value="9876543210" />
            <StyledTextField label="Rental Duration in Months" value="6" />
            <StyledTextField label="Rental Start Date" type="date" value="2025-01-01" />
            <StyledTextField label="Rental End Date" type="date" value="2025-07-01" />
            <StyledTextField label="Order Date" type="date" value="2024-12-20" />
            <StyledTextField label="Company/Institute Name" value="Tech Solutions Ltd." />
            <StyledTextField label="Industry" value="Information Technology" />
          </div>
        </div>

        {/* Column 3: Address */}
        <div style={cardStyle}>
          <div style={cardHeaderContainerStyle}>
            <div style={iconStyle}>🏠</div>
            <h3 style={cardHeaderStyle}>Address</h3>
          </div>
          <div style={fieldsGridStyle}>
            <StyledTextField label="Street" value="1234 Elm Street" />
            <StyledTextField label="Landmark" value="Near Tech Park" />
            <StyledTextField label="Pincode" value="560001" />
            <StyledTextField label="City" defaultValue="Bangalore" />
            <StyledTextField label="State" defaultValue="Karnataka" />
            <StyledTextField label="Country" defaultValue="India" />
          </div>
        </div>
      </div>

      {/* Product Selector and Buttons */}
      <div style={selectedProductSectionStyle}>
        <p style={selectedProductTextStyle}>Selected Products:</p>
        <Button variant="contained" style={productButtonStyle}>
          Update Product
        </Button>
      </div>

      <div style={buttonContainerStyle}>
        <Button variant="outlined" style={cancelBtnStyle}>Cancel</Button>
        <Button variant="contained" style={createBtnStyle}>Update</Button>
      </div>
    </div>
  );
};

// Reusable Field Components
const StyledTextField = ({ label, ...props }) => (
  <TextField
    label={label}
    fullWidth
    size="small"
    InputLabelProps={{ shrink: props.type === "date" || props.value }}
    sx={{ minHeight: '56px' }}
    {...props}
  />
);

const StyledSelectField = ({ label, options, ...props }) => (
  <TextField
    select
    label={label}
    fullWidth
    size="small"
    sx={{ minHeight: '56px' }}
    {...props}
  >
    {options.map((option, index) => (
      <MenuItem key={index} value={option}>
        {option}
      </MenuItem>
    ))}
  </TextField>
);

// Styles (same as previous)
const containerStyle = {
  padding: '2rem',
  fontFamily: '"Inter", "Segoe UI", sans-serif',
  maxWidth: '1400px',
};

const headingStyle = {
  fontSize: '1.5rem',
  fontWeight: 600,
  color: '#1e293b',
  marginBottom: '1.5rem',
};

const formSectionStyle = {
  display: 'flex',
  gap: '1.5rem',
  flexWrap: 'wrap',
};

const cardStyle = {
  flex: '1 1 300px',
  backgroundColor: '#fff',
  padding: '1.5rem',
  borderRadius: '12px',
  border: '1px solid #e2e8f0',
  boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
};

const cardHeaderContainerStyle = {
  display: 'flex',
  alignItems: 'center',
  marginBottom: '1rem',
  borderBottom: '1px solid #e2e8f0',
  paddingBottom: '0.75rem',
};

const iconStyle = {
  fontSize: '1.25rem',
  backgroundColor: '#f1f5f9',
  padding: '0.5rem',
  borderRadius: '8px',
  marginRight: '0.75rem',
};

const cardHeaderStyle = {
  fontSize: '1.125rem',
  fontWeight: 600,
  color: '#1e293b',
  margin: 0,
};

const fieldsGridStyle = {
  display: 'grid',
  gap: '1rem',
  gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
};

const selectedProductSectionStyle = {
  marginTop: '2rem',
};

const selectedProductTextStyle = {
  fontWeight: 500,
  marginBottom: '0.5rem',
};

const productButtonStyle = {
  backgroundColor: '#000',
  color: '#fff',
  textTransform: 'none',
};

const buttonContainerStyle = {
  display: 'flex',
  justifyContent: 'center',
  marginTop: '2rem',
  gap: '1rem',
};

const cancelBtnStyle = {
  textTransform: 'none',
};

const createBtnStyle = {
  backgroundColor: '#3b82f6',
  textTransform: 'none',
};

export default SalesOrdersEditLayoutPage;