import React from 'react';
import {
  Grid,
  Paper,
  Typography,
  TextField,
  MenuItem,
  FormControlLabel,
  Checkbox,
  Button,
} from '@mui/material';

const SalesOrdersAddLayoutPage = () => {
  return (
    <div className="p-6">
      <Typography variant="h6" gutterBottom>
        Create a new Order
      </Typography>
      <Paper elevation={2} className="p-4">
        <Grid container spacing={2}>
          {/* Order Information */}
          <Grid item xs={12} md={4}>
            <Paper elevation={1} className="p-4 bg-gray-50">
              <Typography variant="subtitle1" gutterBottom>
                Order Information:
              </Typography>
              <TextField label="Order ID" fullWidth margin="normal" />
              <TextField label="Order Title" fullWidth margin="normal" />
              <TextField
                select
                label="Quotation Details"
                fullWidth
                margin="normal"
              >
                <MenuItem value="">Select Quotation</MenuItem>
              </TextField>
              <TextField label="Quotation ID" fullWidth margin="normal" />
              <TextField
                select
                label="Transaction Type"
                fullWidth
                margin="normal"
              >
                <MenuItem value="Rent">Rent</MenuItem>
                <MenuItem value="Sale">Sale</MenuItem>
              </TextField>
              <TextField
                select
                label="Payment Type"
                fullWidth
                margin="normal"
              >
                <MenuItem value="Prepaid">Prepaid</MenuItem>
                <MenuItem value="Postpaid">Postpaid</MenuItem>
              </TextField>
              <TextField
                select
                label="Order Status"
                fullWidth
                margin="normal"
              >
                <MenuItem value="Pending">Pending</MenuItem>
                <MenuItem value="Confirmed">Confirmed</MenuItem>
                <MenuItem value="Cancelled">Cancelled</MenuItem>
              </TextField>
              <TextField
                select
                label="Source of Enquiry"
                fullWidth
                margin="normal"
              >
                <MenuItem value="Search Engine">Search Engine</MenuItem>
                <MenuItem value="Referral">Referral</MenuItem>
                <MenuItem value="Walk-in">Walk-in</MenuItem>
              </TextField>
              <TextField label="Owner" fullWidth margin="normal" />
              <TextField
                label="Remarks"
                fullWidth
                margin="normal"
                multiline
                rows={2}
              />
              <TextField
                label="Order Generated By"
                value="rounder"
                fullWidth
                margin="normal"
              />
              <Typography variant="body1" className="mt-2">
                Control:
              </Typography>
              <FormControlLabel
                control={<Checkbox defaultChecked />}
                label="Active Status"
              />
            </Paper>
          </Grid>

          {/* Personal Details */}
          <Grid item xs={12} md={4}>
            <Paper elevation={1} className="p-4 bg-gray-50">
              <Typography variant="subtitle1" gutterBottom>
                Personal Details:
              </Typography>
              <TextField label="First Name" fullWidth margin="normal" />
              <TextField label="Last Name" fullWidth margin="normal" />
              <TextField label="Email ID" fullWidth margin="normal" />
              <TextField label="Phone Number" fullWidth margin="normal" />
              <TextField
                label="Rental Duration in Months"
                fullWidth
                margin="normal"
              />
              <TextField
                label="Rental Start Date"
                type="date"
                fullWidth
                margin="normal"
                InputLabelProps={{ shrink: true }}
              />
              <TextField
                label="Rental End Date"
                type="date"
                fullWidth
                margin="normal"
                InputLabelProps={{ shrink: true }}
              />
              <TextField
                label="Order Date"
                type="date"
                fullWidth
                margin="normal"
                InputLabelProps={{ shrink: true }}
              />
              <TextField
                label="Company/Institute Name"
                fullWidth
                margin="normal"
              />
              <TextField label="Industry" fullWidth margin="normal" />
            </Paper>
          </Grid>

          {/* Address */}
          <Grid item xs={12} md={4}>
            <Paper elevation={1} className="p-4 bg-gray-50">
              <Typography variant="subtitle1" gutterBottom>
                Address:
              </Typography>
              <TextField label="Street" fullWidth margin="normal" />
              <TextField label="Landmark" fullWidth margin="normal" />
              <TextField label="Pincode" fullWidth margin="normal" />
              <TextField
                label="City"
                defaultValue="Bangalore"
                fullWidth
                margin="normal"
              />
              <TextField
                label="State"
                defaultValue="Karnataka"
                fullWidth
                margin="normal"
              />
              <TextField
                label="Country"
                defaultValue="India"
                fullWidth
                margin="normal"
              />
            </Paper>
          </Grid>
        </Grid>
      </Paper>

      {/* Product Selector and Buttons */}
      <div className="mt-6">
        <Typography variant="subtitle1" gutterBottom>
          Selected Products:
        </Typography>
        <Button variant="contained" className="bg-black text-white">
          Select Product
        </Button>

        <div className="mt-6 flex justify-center space-x-4">
          <Button variant="outlined">Cancel</Button>
          <Button variant="contained" color="primary">
            Create
          </Button>
        </div>
      </div>
    </div>
  );
};

export default SalesOrdersAddLayoutPage;
